<a href="https://colab.research.google.com/github/ellyanalinden/breast_cancer_diagnosis/blob/master/breast_cancer_diagnosis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import torch
import torch.nn as nn
from torch.autograd import Variable
import pandas as pd
from sklearn.preprocessing import StandardScaler
from torch.utils.data import Dataset

In [0]:
data = pd.read_csv('Breast_cancer_data.csv')
x = data.iloc[:, 0:-1].values
y_int = list(data.iloc[:, -1])

In [3]:
x

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, 1.203e+03, 1.096e-01],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, 8.581e+02, 8.455e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, 1.265e+03, 1.178e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, 1.810e+02, 5.263e-02]])

In [4]:
print (y_int,)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 

In [5]:
type (y_int)

list

In [0]:
y = np.array(y_int, dtype = 'float64')

In [7]:
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1.,
       1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1.,
       1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1.,
       0., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1.,
       1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1.,
       1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0.,
       1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1.,
       1., 1., 0., 1., 1.

In [0]:
# Normalize data
sc = StandardScaler()
x = sc.fit_transform(x)

In [9]:
x

array([[ 1.09706398, -2.07333501,  1.26993369,  0.9843749 ,  1.56846633],
       [ 1.82982061, -0.35363241,  1.68595471,  1.90870825, -0.82696245],
       [ 1.57988811,  0.45618695,  1.56650313,  1.55888363,  0.94221044],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578,  0.57795264, -0.84048388],
       [ 1.83834103,  2.33645719,  1.98252415,  1.73521799,  1.52576706],
       [-1.80840125,  1.22179204, -1.81438851, -1.34778924, -3.11208479]])

In [10]:
y.shape
# 1 dimension

(569,)

In [0]:
# Transform data to torch tensor
# Change to 2 dimensional to feed data to NN
x = torch.tensor(x)
y = torch.tensor(y).unsqueeze(1)

In [12]:
print (x.shape, x.dtype)
print (y.shape, y.dtype)

torch.Size([569, 5]) torch.float64
torch.Size([569, 1]) torch.float64


In [0]:
x = Variable(x)
y = Variable(y)

In [0]:
# Creating Dataset
class Dataset(Dataset):
  
  def __init__(self,x,y):
    self.x = x
    self.y = y
  
  def __getitem__(self, index):
    return self.x[index], self.y[index]
  
  def __len__(self):
    return len(self.x)

In [0]:
dataset = Dataset(x,y)

In [16]:
print (dataset.x.shape)
print (dataset.y.shape)

torch.Size([569, 5])
torch.Size([569, 1])


In [0]:
# Creating train loader
train_loader = torch.utils.data.DataLoader(dataset=dataset,
                                          batch_size = 32,
                                          shuffle = True)

In [18]:
len(train_loader)

18

In [19]:
18*32

576

In [20]:
print ("There is {} batches in the dataset".format(len(train_loader)))
shown = 0
for(x,y) in train_loader:
  if shown == 1:
    break
  print("For one iteration (batch), there is:")
  print("Data:  {} , Type: {} ".format(x.shape,x.dtype))
  print("Labels:  {} , Type: {} ".format(y.shape,y.dtype))
  shown += 1

There is 18 batches in the dataset
For one iteration (batch), there is:
Data:  torch.Size([32, 5]) , Type: torch.float64 
Labels:  torch.Size([32, 1]) , Type: torch.float64 


In [0]:
# Build the NN
class Model(nn.Module):
  def __init__(self):
    super(Model,self).__init__()
    self.fc1 = torch.nn.Linear(x.shape[1], 3)
    self.fc2 = torch.nn.Linear(3,1)
    self.sigmoid = torch.nn.Sigmoid()
    
  def forward(self, x):
    out = self.fc1(x)
    out = self.sigmoid(out)
    out = self.fc2(out)
    out = self.sigmoid(out)
    return out

In [44]:
net = Model()
criterion = torch.nn.BCELoss(size_average=True)
optimizer = torch.optim.SGD(net.parameters(), lr = 0.01)

/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='elementwise_mean' instead.
  warnings.warn(warning.format(ret))


In [45]:
net.parameters

<bound method Module.parameters of Model(
  (fc1): Linear(in_features=5, out_features=3, bias=True)
  (fc2): Linear(in_features=3, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)>

In [48]:
# Training the network
num_epochs = 50
for epoch in range(num_epochs):
  for inputs, labels in train_loader:
    inputs = Variable(inputs.float())
    labels = Variable(labels.float())
    output = net(inputs)
    optimizer.zero_grad()
    loss = criterion(output, labels)
    loss.backward()
    optimizer.step()
    
  # Accuracy
  # After we have looped through all our dataset, we can evaluate on the last iteration of each epoch
  # 'Output' is the network's output of the last minibatch of the epoch, and labels is the corresponding batch labels
  output = (output>0.5).float()
  correct = (output == labels).float().sum()
  print("Epoch {}/{}, Loss: {:.3f}, Accuracy: {:.3f}".format(epoch+1, num_epochs, loss.data[0], correct/output.shape[0]))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:17: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number


Epoch 1/50, Loss: 0.178, Accuracy: 0.960
Epoch 2/50, Loss: 0.247, Accuracy: 0.880
Epoch 3/50, Loss: 0.230, Accuracy: 0.880
Epoch 4/50, Loss: 0.251, Accuracy: 0.840
Epoch 5/50, Loss: 0.176, Accuracy: 0.920
Epoch 6/50, Loss: 0.281, Accuracy: 0.840
Epoch 7/50, Loss: 0.134, Accuracy: 0.960
Epoch 8/50, Loss: 0.269, Accuracy: 0.880
Epoch 9/50, Loss: 0.205, Accuracy: 0.880
Epoch 10/50, Loss: 0.181, Accuracy: 0.960
Epoch 11/50, Loss: 0.176, Accuracy: 0.920
Epoch 12/50, Loss: 0.250, Accuracy: 0.800
Epoch 13/50, Loss: 0.342, Accuracy: 0.840
Epoch 14/50, Loss: 0.192, Accuracy: 0.920
Epoch 15/50, Loss: 0.166, Accuracy: 0.920
Epoch 16/50, Loss: 0.154, Accuracy: 1.000
Epoch 17/50, Loss: 0.140, Accuracy: 0.960
Epoch 18/50, Loss: 0.241, Accuracy: 0.840
Epoch 19/50, Loss: 0.116, Accuracy: 0.960
Epoch 20/50, Loss: 0.265, Accuracy: 0.920
Epoch 21/50, Loss: 0.243, Accuracy: 0.920
Epoch 22/50, Loss: 0.212, Accuracy: 0.880
Epoch 23/50, Loss: 0.129, Accuracy: 0.960
Epoch 24/50, Loss: 0.270, Accuracy: 0.840
E